"""core/voice_preview.py — one-shot Gemini TTS preview for the voice picker.

GeminiLiveSession (core/live_voice.py) only speaks through a long-lived
bidirectional session with the voice locked in at connect time — there's no
way to ask it "say one line in voice X" on demand, and its model
(gemini-2.5-flash-native-audio-preview) doesn't support the one-shot
generate_content call at all (confirmed: it 404s outside the Live API). This
module hits Gemini's single-turn speech-generation endpoint instead, so
Preferences can play a short "Hey, I'm <name>." sample the moment a voice is
selected, without opening a full Live API session (no mic capture, no tool
wiring).

The dedicated TTS-preview model's free-tier quota is a hard 10 requests/day
*total* (confirmed directly: 429 RESOURCE_EXHAUSTED,
GenerateRequestsPerDayPerProjectPerModel-FreeTier, quotaValue=10) — nowhere
near enough for one call per dropdown click. So lookups check, in order:
(1) the bundled clip shipped with the app (all 30 voices at the default
accent, pre-generated by scripts/generate_voice_previews.py — the common
case costs zero API calls), (2) a writable on-disk cache for anything
missing from the bundle (a voice added to core/voices.py since the bundle
was last regenerated, or any non-default accent — those are never bundled,
see _bundled_path()), (3) only then a live API call, whose result is
written into that cache so it's a one-time cost per voice+accent
combination per machine, not per click.

Model: gemini-3.1-flash-tts-preview (migrated from
gemini-2.5-flash-preview-tts once its daily quota was exhausted — the two
models turned out to track quota in separate buckets, so switching also
happened to unblock bundling immediately rather than waiting on 2.5's
quota to reset).

Source: https://ai.google.dev/gemini-api/docs/generate-content/speech-generation
"""
from __future__ import annotations

import re
import sys
import threading
import wave
from pathlib import Path

import numpy as np
import sounddevice as sd

_PREVIEW_MODEL = "gemini-3.1-flash-tts-preview"
_RATE_RE = re.compile(r"rate=(\d+)")

# Bumped on every preview request; a request whose token is stale by the time
# its network round-trip finishes is dropped instead of played, so rapidly
# clicking through voices can't play them back out of order.
_lock = threading.Lock()
_generation = 0


def preview_text(voice_name: str) -> str:
    return f"Hey, I'm {voice_name}."


def _preview_contents(voice_name: str, accent: str, style: str, pace: str) -> str:
    from core.accents import accent_instruction
    from core.styles import style_instruction
    from core.pace import pace_instruction

    fragments = []
    if instr := style_instruction(style):
        fragments.append(f"in {instr}")
    if instr := pace_instruction(pace):
        fragments.append(f"at {instr}")
    if instr := accent_instruction(accent):
        fragments.append(f"with {instr}")

    text = preview_text(voice_name)
    if not fragments:
        return text
    # Validated phrasing (user-confirmed on Sadaltager/newscaster/British):
    # "In a newscaster style, at a normal pace, with a British accent, say: ..."
    lead = ", ".join(fragments)
    return f"{lead[0].upper()}{lead[1:]}, say: {text}"


def _install_dir() -> Path:
    """Read-only install/repo root, where the bundled preview clips live
    (core/voice_previews/*.wav). Duplicated from main.py::get_base_dir()
    rather than imported — this repo's convention for small base-dir/OS
    helpers, see CLAUDE.md."""
    if getattr(sys, "frozen", False):
        exe_dir = Path(sys.executable).resolve().parent
        if sys.platform == "darwin":
            # See main.py::get_base_dir() — macOS BUNDLE puts `datas` under
            # Contents/Resources, not next to the executable.
            resources = exe_dir.parent / "Resources"
            if resources.exists():
                return resources
            return exe_dir
        # See main.py::get_base_dir() — Windows onedir datas don't actually
        # land flat next to the exe despite mark48.spec's
        # contents_directory='.', so use sys._MEIPASS instead of assuming
        # a flat layout.
        meipass = getattr(sys, "_MEIPASS", None)
        if meipass:
            return Path(meipass)
        return exe_dir
    return Path(__file__).resolve().parent.parent


def _is_default(accent: str, style: str, pace: str) -> bool:
    return accent == "default" and style == "default" and pace == "default"


def _cache_filename(voice_name: str, accent: str, style: str, pace: str) -> str:
    # All-default is bundled/cached under the bare voice name — any other
    # combination (never pre-bundled, see module docstring) gets a distinct,
    # collision-free cache key encoding which dimensions are non-default.
    if _is_default(accent, style, pace):
        return f"{voice_name}.wav"
    parts = [voice_name]
    if style  != "default": parts.append(f"style-{style}")
    if pace   != "default": parts.append(f"pace-{pace}")
    if accent != "default": parts.append(f"accent-{accent}")
    return "__".join(parts) + ".wav"


def _bundled_path(voice_name: str, accent: str, style: str, pace: str) -> Path | None:
    if not _is_default(accent, style, pace):
        return None  # bundle only ever ships all-default clips
    return _install_dir() / "core" / "voice_previews" / _cache_filename(voice_name, accent, style, pace)


def _cache_path(voice_name: str, accent: str, style: str, pace: str) -> Path:
    """Writable fallback cache, separate from the read-only bundle dir (a
    packaged install's own directory often isn't user-writable). Same
    per-user app-data location memory/config_manager.py resolves for
    api_keys.json/preferences.json."""
    from memory.config_manager import CONFIG_DIR
    return CONFIG_DIR / "voice_previews_cache" / _cache_filename(voice_name, accent, style, pace)


def _read_wav(path: Path) -> tuple[np.ndarray, int]:
    with wave.open(str(path), "rb") as w:
        rate = w.getframerate()
        pcm  = w.readframes(w.getnframes())
    return np.frombuffer(pcm, dtype=np.int16), rate


def write_wav(path: Path, pcm_bytes: bytes, sample_rate: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with wave.open(str(path), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(sample_rate)
        w.writeframes(pcm_bytes)


def synthesize(
    api_key: str, voice_name: str,
    accent: str = "default", style: str = "default", pace: str = "default",
) -> tuple[bytes, int]:
    """One live network call to Gemini's single-turn TTS endpoint. Returns
    (raw 16-bit PCM mono bytes, sample_rate). Raises on failure — callers
    decide how to handle quota/network errors. Used both by play_preview()'s
    cache-miss fallback and by scripts/generate_voice_previews.py to build
    the bundled set (always all-default — see module docstring)."""
    from google import genai
    from google.genai import types

    client = genai.Client(api_key=api_key, http_options={"api_version": "v1beta"})
    response = client.models.generate_content(
        model=_PREVIEW_MODEL,
        contents=_preview_contents(voice_name, accent, style, pace),
        config=types.GenerateContentConfig(
            response_modalities=["AUDIO"],
            speech_config=types.SpeechConfig(
                voice_config=types.VoiceConfig(
                    prebuilt_voice_config=types.PrebuiltVoiceConfig(voice_name=voice_name)
                ),
            ),
        ),
    )

    part = response.candidates[0].content.parts[0]
    audio_bytes = part.inline_data.data
    mime = part.inline_data.mime_type or ""
    rate_match = _RATE_RE.search(mime)
    sample_rate = int(rate_match.group(1)) if rate_match else 24000
    return audio_bytes, sample_rate


def stop_preview() -> None:
    """Stop any preview currently playing and invalidate in-flight requests
    (their audio will be dropped instead of played when they land). Safe to
    call even when nothing is playing — e.g. on every overlay close."""
    global _generation
    with _lock:
        _generation += 1
    sd.stop()


def play_preview(
    api_key: str, voice_name: str,
    accent: str = "default", style: str = "default", pace: str = "default",
) -> None:
    """Play a short "Hey, I'm <voice_name>." sample, optionally in a chosen
    accent/style/pace (see core/accents.py, core/styles.py, core/pace.py —
    each embedded as a prompt instruction, Gemini's speech APIs have no
    structured fields for any of these). Blocking — call from a background
    thread, not the UI thread."""
    global _generation
    with _lock:
        _generation += 1
        my_generation = _generation

    samples = None
    candidates = [p for p in (_bundled_path(voice_name, accent, style, pace),
                               _cache_path(voice_name, accent, style, pace)) if p is not None]
    for path in candidates:
        if path.exists():
            samples, sample_rate = _read_wav(path)
            break

    if samples is None:
        audio_bytes, sample_rate = synthesize(api_key, voice_name, accent, style, pace)
        samples = np.frombuffer(audio_bytes, dtype=np.int16)
        try:
            write_wav(_cache_path(voice_name, accent, style, pace), audio_bytes, sample_rate)
        except OSError as e:
            print(f"[VoicePreview] Couldn't cache {voice_name!r}/{accent!r}/{style!r}/{pace!r}: {e}")

    with _lock:
        if my_generation != _generation:
            return  # superseded by a newer selection — don't play a stale voice

    sd.play(samples, sample_rate)
    sd.wait()
